name: Publish to Artifact Registry

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and push to Artifact Registry
      run: |
        # Build and package your code (if necessary)

        # Example: npm install && npm run build

        # Push the artifacts to Artifact Registry
        gcloud artifacts print-settings npm --location=europe-west1 --repository=apis-base
        gcloud auth configure-docker -q
        docker push europe-west1-docker.pkg.dev/snappy-density-406712/apis-base/api-fe-support:latest
